#!/bin/bash
set -e

# CoreTrace Agent Installation Script
# Repository: https://github.com/mithunkumar07/coretrace
# Usage: curl -sSL https://raw.githubusercontent.com/mithunkumar07/coretrace/main/coretrace-agent/install.sh | sudo bash

# Configuration
AGENT_VERSION="${AGENT_VERSION:-1.0.4}"
GITHUB_REPO="mithunkumar07/coretrace"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/coretrace"
LOG_DIR="/var/log/coretrace"
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    log_error "Please run as root (use sudo)"
    exit 1
fi

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════╗"
echo "║     CoreTrace Agent Installation Script v${AGENT_VERSION}       ║"
echo "║     SSH Session & File Monitoring                     ║"
echo "╚════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Detect architecture
ARCH=$(uname -m)
case $ARCH in
    x86_64)
        ARCH="amd64"
        ;;
    aarch64)
        ARCH="arm64"
        ;;
    *)
        log_error "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

log_info "Detected architecture: $ARCH"
log_info "Install directory: $INSTALL_DIR"
log_info "Config directory: $CONFIG_DIR"
log_info "Log directory: $LOG_DIR"
echo ""

# Step 1: Create directories
log_step "Creating directories..."
mkdir -p "$CONFIG_DIR"
mkdir -p "$LOG_DIR/sessions"
chmod 755 "$LOG_DIR"
log_info "Directories created"
echo ""

# Step 2: Download binary from GitHub releases
log_step "Downloading CoreTrace Agent v${AGENT_VERSION}..."

# Construct download URL
BINARY_NAME="coretrace-agent-linux-${ARCH}"
DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/v${AGENT_VERSION}/${BINARY_NAME}"
CHECKSUM_URL="https://github.com/${GITHUB_REPO}/releases/download/v${AGENT_VERSION}/checksums.txt"

log_info "Downloading from: ${DOWNLOAD_URL}"

# Download binary with retry logic
download_with_retry() {
    local url=$1
    local output=$2
    local retries=3
    local count=0
    
    while [ $count -lt $retries ]; do
        if curl -fsSL --connect-timeout 10 --max-time 60 "$url" -o "$output" 2>/dev/null; then
            return 0
        fi
        count=$((count + 1))
        log_warn "Download attempt $count failed, retrying..."
        sleep 2
    done
    return 1
}

# Download binary
if ! download_with_retry "$DOWNLOAD_URL" "${TEMP_DIR}/${BINARY_NAME}"; then
    log_error "Failed to download binary after 3 attempts"
    log_error "Please check:"
    log_error "  - Version exists: https://github.com/${GITHUB_REPO}/releases/tag/v${AGENT_VERSION}"
    log_error "  - Architecture supported: ${ARCH}"
    exit 1
fi

# Download and verify checksum
log_info "Verifying checksum..."
if download_with_retry "$CHECKSUM_URL" "${TEMP_DIR}/checksums.txt"; then
    cd "$TEMP_DIR"
    if sha256sum -c checksums.txt --ignore-missing 2>/dev/null | grep -q "${BINARY_NAME}: OK"; then
        log_info "Checksum verified"
    else
        log_warn "Checksum verification failed, but continuing with installation"
    fi
    cd - > /dev/null
else
    log_warn "Could not download checksums, skipping verification"
fi

# Install binary
log_info "Installing binary to ${INSTALL_DIR}..."
cp "${TEMP_DIR}/${BINARY_NAME}" "$INSTALL_DIR/coretrace-agent"
chmod +x "$INSTALL_DIR/coretrace-agent"
log_info "Binary installed successfully"
echo ""

# Step 3: Create config
log_step "Creating configuration..."
if [ ! -f "$CONFIG_DIR/config.yaml" ]; then
    cat > "$CONFIG_DIR/config.yaml" << 'EOF'
# CoreTrace Agent Configuration
# Generated by install.sh

agent:
  name: "coretrace-agent"
  version: "1.0.0"
  debug: false

logging:
  level: "info"
  format: "json"
  output: "stdout"

ssh:
  enabled: true
  auth_log_paths:
    - "/var/log/auth.log"
    - "/var/log/secure"
  session_timeout: "24h"
  max_sessions: 1000

file:
  enabled: true
  watch_paths:
    - "/etc"
    - "/home"
    - "/root"
    - "/var/log"
    - "/opt"
    - "/usr/local/bin"
    - "/tmp"
    - "/var/tmp"
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - ".git/*"
    - "node_modules/*"
    - ".cache/*"
  max_watched_files: 10000

session_logging:
  enabled: true
  sessions_dir: "/var/log/coretrace/sessions"
  max_session_duration: "24h"
  cleanup_interval: "1h"
  rotation:
    max_size_mb: 100
    max_backups: 10
    max_age_days: 30
    compress: true
EOF
    log_info "Configuration created at $CONFIG_DIR/config.yaml"
else
    log_warn "Configuration already exists, skipping"
fi
echo ""

# Step 4: Setup auditd
log_step "Setting up auditd for command monitoring..."

# Install auditd if not present
if ! command -v auditctl &> /dev/null; then
    log_info "Installing auditd..."
    
    if command -v apt-get &> /dev/null; then
        apt-get update -qq
        apt-get install -y -qq auditd audispd-plugins || {
            log_warn "Could not install auditd via apt"
        }
    elif command -v yum &> /dev/null; then
        yum install -y audit || {
            log_warn "Could not install auditd via yum"
        }
    elif command -v dnf &> /dev/null; then
        dnf install -y audit || {
            log_warn "Could not install auditd via dnf"
        }
    else
        log_warn "Could not install auditd automatically"
    fi
else
    log_info "auditd already installed"
fi

# Configure auditd rules
if command -v auditctl &> /dev/null; then
    log_info "Configuring auditd rules..."
    
    # Remove old rules to avoid duplicates
    auditctl -d always,exit -F arch=b64 -S execve -S execveat -k session_monitoring 2>/dev/null || true
    auditctl -d always,exit -F arch=b32 -S execve -S execveat -k session_monitoring 2>/dev/null || true
    
    # Add new rules
    auditctl -a always,exit -F arch=b64 -S execve -S execveat -k session_monitoring 2>/dev/null || true
    auditctl -a always,exit -F arch=b32 -S execve -S execveat -k session_monitoring 2>/dev/null || true
    
    # Make persistent
    mkdir -p /etc/audit/rules.d
    cat > /etc/audit/rules.d/coretrace.rules << 'EOF'
# CoreTrace command monitoring rules
-a always,exit -F arch=b64 -S execve -S execveat -k session_monitoring
-a always,exit -F arch=b32 -S execve -S execveat -k session_monitoring
EOF
    
    if command -v augenrules &> /dev/null; then
        augenrules --load 2>/dev/null || true
    fi
    
    # Start/restart auditd
    if command -v systemctl &> /dev/null; then
        systemctl restart auditd 2>/dev/null || systemctl start auditd 2>/dev/null || true
        systemctl enable auditd 2>/dev/null || true
    fi
    
    log_info "Auditd configured successfully"
else
    log_warn "auditctl not found. Command monitoring will be disabled."
    log_warn "SSH and file monitoring will still work."
fi
echo ""

# Step 5: Create systemd service
log_step "Creating systemd service..."

cat > /etc/systemd/system/coretrace-agent.service << EOF
[Unit]
Description=CoreTrace Agent - SSH Session Monitoring
Documentation=https://docs.coretrace.io
After=network.target auditd.service
Wants=auditd.service

[Service]
Type=simple
ExecStart=$INSTALL_DIR/coretrace-agent monitor --config $CONFIG_DIR/config.yaml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=coretrace-agent

# Security settings
NoNewPrivileges=false
ProtectSystem=false
ProtectHome=false

# Resource limits
LimitNOFILE=65536
MemoryMax=512M
CPUQuota=50%

[Install]
WantedBy=multi-user.target
EOF

if command -v systemctl &> /dev/null; then
    systemctl daemon-reload
    systemctl enable coretrace-agent
    log_info "Systemd service created and enabled"
else
    log_warn "systemd not found. You'll need to start the agent manually."
fi
echo ""

# Step 6: Start the service
log_step "Starting CoreTrace Agent..."

if command -v systemctl &> /dev/null; then
    systemctl start coretrace-agent
    sleep 2
    
    if systemctl is-active --quiet coretrace-agent; then
        log_info "CoreTrace Agent is running!"
    else
        log_error "Failed to start CoreTrace Agent"
        log_error "Check logs: journalctl -u coretrace-agent -n 50"
        exit 1
    fi
else
    log_warn "Please start the agent manually:"
    log_warn "  $INSTALL_DIR/coretrace-agent monitor --config $CONFIG_DIR/config.yaml &"
fi
echo ""

# Final summary
echo -e "${GREEN}"
echo "╔════════════════════════════════════════════════════════╗"
echo "║        Installation Complete!                          ║"
echo "╚════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
log_info "CoreTrace Agent v${AGENT_VERSION} installed successfully"
echo ""
echo "📁 Installation Summary:"
echo "   Binary:     $INSTALL_DIR/coretrace-agent"
echo "   Config:     $CONFIG_DIR/config.yaml"
echo "   Logs:       $LOG_DIR/sessions/"
echo "   Service:    systemd (coretrace-agent)"
echo ""
echo "🚀 Quick Start:"
echo "   View status:     systemctl status coretrace-agent"
echo "   View logs:       journalctl -u coretrace-agent -f"
echo "   Session logs:    ls -la $LOG_DIR/sessions/\$(date +%Y-%m-%d)/"
echo "   Edit config:     nano $CONFIG_DIR/config.yaml"
echo "   Restart:         systemctl restart coretrace-agent"
echo ""
echo "🧪 Test the agent:"
echo "   1. SSH into this server from another machine"
echo "   2. Run some commands (ls, pwd, cat /etc/passwd)"
echo "   3. Check session logs:"
echo "      tail -f $LOG_DIR/sessions/\$(date +%Y-%m-%d)/*.jsonl"
echo ""
echo "📚 Documentation:"
echo "   Full guide:      cat DEPLOY.md"
echo "   Configuration:   cat $CONFIG_DIR/config.yaml"
echo ""
